composer.json, config/install/simple_sitemap.bundle_settings.node.content_page.yml, config/install/simple_sitemap.settings.yml, droopler.info.yml
Simple sitemap module + yml config for node type
=> Issue #30223: Enable XML sitemap

modules/custom/d_blog/config/install/field.field.node.blog_post.field_blog_main_image.yml, modules/custom/d_blog/config/install/field.field.paragraph.d_p_blog_image.field_d_image.yml, modules/custom/d_blog/config/install/field.storage.node.field_blog_main_image.yml, modules/custom/d_blog/d_blog.info.yml
(cherry picked from commit 924111c)
=> #30764 Blog - fix bug with UUID on d_blog install

modules/custom/d_p/js/d_p.js
W sumie to timout na resize chyba faktycznie zalatwia sprawe.
=> DROOP-12: Fix backstretch image resize

themes/custom/droopler_theme/templates/layout/page.html.twig
added condition to verify user permission
=> Droop 130 admin tab visible for anonymous

modules/custom/d_content/modules/d_content_init/d_content_init.module
=> Droop 132 entity instead of node

modules/custom/d_blog/d_blog.info.yml, modules/custom/d_blog/d_blog.install, modules/custom/d_blog/d_blog.module, modules/custom/d_blog/translations/d_blog-8.x-1.4.pl.po
added .po file for user interface translation in d_blog module
=> #issue DROOP-230-d-blog-add-translation: 

modules/custom/d_p_carousel/d_p_carousel.module, modules/custom/d_p_carousel/js/d_p_carousel.js, modules/custom/d_p_carousel/templates/field--field-d-p-cs-item-reference.html.twig
=> DROOP-87: Only one instance of d_image in carousel

themes/custom/droopler_theme/scss/components/_d_blog.scss
Add darker color for b and strong tags on blog, fix problems with smaller text on ul and ol tags on blog
=> #issue DROOP-72: Fix blog styling

modules/custom/d_content/src/Routing/ContactAlterRouteSubscriber.php
DROOP-236-improve-ContactAlterRouteSubscriber:handle uninstall contact module
=> DROOP-236-improve-ContactAlterRouteSubscriber

modules/custom/d_blog/config/install/pathauto.pattern.node_blog_pattern.yml
=> DROOP-240: Add pathauto for blog posts to blog/post_title

modules/custom/d_lang_dropdown/js/d_lang_dropdown.js
Shoud not use absolute block ID, because it depend on the active theme name.
It should be class selector here.
=> #177 d_lang_dropdown.js selector problem

droopler.install, modules/custom/d_update/updates.yml
Made sure that d_p and it's new dependencies are enabled and imported, then proceeding to install required custom modules based on droopler.info.yml.
=> DD-274 Error while importing configs for uninstalled modules

themes/custom/droopler_theme/scss/layout/_bottom_footer.scss
Fixed justifying of menu items. Added variable for menu link padding.
=> DD-253 - Corrected menu positioning.

themes/custom/droopler_theme/scss/components/_buttons.scss, themes/custom/droopler_theme/scss/components/_d_p_form.scss, themes/custom/droopler_theme/scss/components/_d_product_page.scss, themes/custom/droopler_theme/scss/components/_d_products.scss, themes/custom/droopler_theme/scss/components/_geysir_overrides.scss
Changed from extending bootstrap classes in lieu of using bootstrap mixins for effective compiled styles size reduction.
=> DD-267 Reducing style.css filesize.

UPDATE.md, themes/custom/droopler_theme/scss/config/_old_color_scheme.scss
=> DD-188 Instruction for restoring old color scheme

themes/custom/droopler_theme/scss/components/_d_p_subscribe.scss
Added opacity for iframe inside subscribe_file paragraph.
=> DD-279 No overlay for video inside subscribe file paragraph

themes/custom/droopler_theme/scss/components/_d_blog.scss
Restored Learn more font-size to default.
=> DD-286 Correction of learn more font size

composer.json, modules/custom/d_media/config/install/core.entity_view_display.media.d_video.gallery_item.yml, modules/custom/d_media/templates/d-media-video-embed.html.twig, themes/custom/droopler_theme/droopler_theme.libraries.yml, themes/custom/droopler_theme/droopler_theme.theme, themes/custom/droopler_theme/js/ie-compatibility.js, themes/custom/droopler_theme/scss/components/_d_blog.scss, themes/custom/droopler_theme/scss/components/_d_blog_listing.scss, themes/custom/droopler_theme/scss/components/_d_media.scss, themes/custom/droopler_theme/scss/components/_d_p_gallery.scss
Created js for handling the library. Modified styles according to the object-fit library manual. Added ie-compatibility library. Created function to detect user browser and ie-compatibility library for further extensions.
=> DD-263 Add library to allow usage of object-fit elements.

modules/custom/d_media/config/install/core.entity_view_display.media.d_video.gallery_item.yml, modules/custom/d_media/templates/d-media-video-embed.html.twig, themes/custom/droopler_theme/scss/components/_d_media.scss, themes/custom/droopler_theme/scss/components/_d_p_gallery.scss
Moved reactive video styles to d_media. Modified template for original image. Added gallery item display mode to video media entity.
=> DD-281 Video not displaying correctly inside gallery paragraph.

composer.json, droopler.install, modules/custom/d_blog/config/install/node.type.blog_post.yml, modules/custom/d_content/config/install/node.type.content_page.yml
Changed geysir version to the newest dev version, seems to resolve the issue.
=> DD-271 Crash on blog preview

droopler.install, modules/custom/d_blog/config/install/node.type.blog_post.yml, modules/custom/d_content/config/install/node.type.content_page.yml, modules/custom/d_media/config/install/core.entity_view_display.media.d_image.counter.yml, modules/custom/d_media/config/install/core.entity_view_display.media.d_video.counter.yml, modules/custom/d_media/config/install/core.entity_view_mode.media.counter.yml, modules/custom/d_p_counters/config/install/core.entity_view_display.paragraph.d_p_group_of_counters.default.yml
In order to autoplay the video has to be muted. Additional view mode has been added.
=> DD-280 Video not autoplaying inside counters paragraph.

modules/custom/d_mautic/d_mautic.info.yml
instalację modułu przy buildowaniu przypadkowo scommitowałam na gałęzi DD-278
=> DD-304 update d_mautic settings and infos

modules/custom/d_content/modules/d_content_init/d_content_init.api.php, modules/custom/d_content/modules/d_content_init/d_content_init.module, modules/custom/d_product/d_product_init/d_product_init.module
Added Search API indexing after installation.
=> DD-323 No products in demo

droopler.install
Covers edge case when content type has been deleted and the providing module hasn't.
=> DROOP-329 Fix bugs during updates.

modules/custom/d_p_counters/templates/field--paragraph--field-d-counter-reference--d-p-group-of-counters.html.twig
another twig with bad order of tag closing and conditional block ending :pray:
=> #0 fixing incorrect tags closing

modules/custom/d_update/src/Updater.php
Added change handling to Updater::modifyConfig.
=> Added change existing config to updater.

modules/custom/d_social_media/js/last-element-in-a-row.js
Depending on the context, the elements will be empty. having empty elements creates JS errors "Uncaught TypeError: Cannot read property 'className' of undefined".
Wrapped the code in check for the elements length to prevent errors.
Please review.
=> Make sure the iterations don't run and class not checked on empty els.

droopler.info.yml
Update Droopler version to stable
=> Update master from 2.1

droopler.info.yml
Gdyby ktoś miał wątpliwości dlaczego tak to:
https://www.drupal.org/node/2952947
=> Issue #3159013 by sayco: (v 2.2) Review why some modules are optional

composer.json
=> #3207385 Add missing jquery-ui-touch-punch library

modules/custom/d_color/src/Element/ColorElement.php, modules/custom/d_content/modules/d_content_init/src/ContentInitManagerMedia.php, modules/custom/d_content/modules/d_content_init/src/Services/ConfigUpdate.php, modules/custom/d_demo/src/Service/ThemeLogoService.php, modules/custom/d_p_subscribe_file/src/Commands/SubscribeSanitizeCommand.php
Drupal 9.4 compatibility fixes.
=> DROOP-752: Fix compatibility issues

droopler.info.yml
Fixed Problem with unmet dependencies: block.block.pagetitle (ctools)
=> Issue #3301685 by gpietrzak: (v 3.1) Problem with unmet dependencies
